### PR TITLE
fix: package-lock.json resolved dependencies

### PR DESCRIPTION
**Pull request by RichAyotte**
## Summary
Resolve `package-lock.json` dependencies.

When running `npm ci`, the `package-lock.json` was updated automatically. The NPM version used was `9.1.2`. The change is quite large and so it's probably easier to reproduce the change locally to verify the files validity.

### Testing
- Package installation was successful
- Automated tests pass. `npm test`
- Ran the test dApp successfully

- [x] Your code builds cleanly without any errors or warnings

### CODE REVIEW

**Comment by egarson** [comment]
Hello,
Could you please explain further what this change intends?
By design, `npm ci` does not change `package.json`, nor by extension `package-lock.json`. Did you run `npm i` by any chance? That command will update those files.
Cheers,
Edward

**Comment by RichAyotte** [comment]
> Hello, Could you please explain further what this change intends?
For some odd reason, running `npm ci` seemed to be altering package-lock.json but in fact it was lerna bootstrap.

> By design, `npm ci` does not change `package.json`, nor by extension `package-lock.json`.
That's true and I've confirmed this with the official npm docs.

>Did you run `npm i` by any chance? That command will update those files. Cheers, Edward
I did not. Lerna bootstrap on the other hand was.

I've opened a new PR to address the lerna bootstrap issue. https://github.com/ecadlabs/taquito/pull/2178

**Comment by RichAyotte** [comment]
Closing in favour of https://github.com/ecadlabs/taquito/pull/2178

**Comment by RichAyotte** [comment]
package-lock.json fixed in https://github.com/ecadlabs/taquito/pull/2202

**Pull request closed without merging**
