### PR TITLE
add extra case to handle axios-fetch-adapter error response

### LINKED ISSUE #2187: BigMapAbstraction.get method no longer catches 404 errors
**Description**
I assume the issue appeared since the introduction of `vespaiach/axios-fetch-adapter`.

In the `BigMapAbstraction` class, the method `get` tries to handle `404` responses.
However, 404 responses in the browser no longer trigger an exception of type `HttpResponseError` but `HttpRequestFailed`.

As a result, the exception is thrown instead of returning `undefined`.

**Steps To Reproduce**
1. Be in a Browser environment
2. Try to load a non-existent key from a bigmap.

**Expected behavior**
The function should return `undefined`

**Actual behavior**
The function throws an exception

**Desktop (please complete the following information):**
 - any browser environment

Thank you.

### PR DESCRIPTION
**Pull request by dsawali**
closes #2187 
Thank you for your contribution to Taquito.

Before submitting this PR, please make sure:

- [x] Your code builds cleanly without any errors or warnings
- [ ] You have added unit tests
- [x] You have added integration tests (if relevant/appropriate)
- [ ] All public methods or types have TypeDoc coverage with a complete description, and ideally an @example
- [ ] You have added or updated corresponding documentation
- [ ] If relevant, you have written a first draft summary describing the change for inclusion in Release Notes. 

## Release Note Draft Snippet

__If relevant, please write a summary of your change that will be suitable for
inclusion in the Release Notes for the next Taquito release.__

### CODE REVIEW

**Comment by danielelisi** [comment]
Could you add a unit test to confirm that when `axios-fetch-adapter` is used the correct error is thrown on 404 requests?

**Comment by dsawali** [comment]
> Could you add a unit test to confirm that when `axios-fetch-adapter` is used the correct error is thrown on 404 requests?

I think we can do that, but I'll need to change the adapter to be a param so we have control over that in the unit test. Otherwise we wouldn't be able to mock the `isNode` value. Will amend.

**Review by danielelisi — APPROVED** [review]

**Review by zainen — APPROVED** [review]
lgtm nice work around. guessing we will chat more about it next week

**Comment by dsawali** [comment]
for visibility, the workaround was to also fork the fetch adapter and update it so that it suits our needs until Axios decides to provide native support for fetch based requests

Forked repo: https://github.com/ecadlabs/axios-fetch-adapter

**Pull request merged**
