### PR TITLE
Bundle taquito beacon wallet

### PR DESCRIPTION
**Pull request by hui-an-yang**
Adding taquito-beacon-wallet bundling to ci 

Thank you for your contribution to Taquito.

Before submitting this PR, please make sure:

- [x] Your code builds cleanly without any errors or warnings
- [x] You have run the linter against the changes
- [ ] You have added unit tests (if relevant/appropriate)
- [ ] You have added integration tests (if relevant/appropriate)
- [ ] All public methods or types have TypeDoc coverage with a complete description, and ideally an @example
- [ ] You have added or updated corresponding documentation
- [ ] If relevant, you have written a first draft summary describing the change for inclusion in Release Notes. 

In this PR, please also make sure: 

- [ ] You have linked this PR to the issue by putting `closes #TICKETNUMBER` in the description box (when applicable)
- [ ] You have added a concise description on your changes
## Release Note Draft Snippet

__If relevant, please write a summary of your change that will be suitable for
inclusion in the Release Notes for the next Taquito release.__

### CODE REVIEW

**Comment by dsawali** [comment]
@hui-an-yang have we tested whether the beacon wallet bundle is importable and usable?

**Comment by oldominion** [comment]
I've tested the bundle described here, and successfully been able to do what I need to do from a JS environment (Blazor WASM, which has only JS interop).

importing the bundles in index.html:
`<script src="_content/BeaconWalletComponent/taquito.min.js"></script>
<script src="_content/BeaconWalletComponent/taquito_beacon_wallet.js"></script>`

In a beaconWrapper.js file that I call via interop:
`const taquitoTezos = new taquito.TezosToolkit("<RPC_URL>");
const taquitoWallet = new taquito_beacon_wallet.BeaconWallet({
            name: dAppName,
            preferredNetwork: networkType
        });
taquitoTezos.setWalletProvider(taquitoWallet);
`

Is there a reason this PR was closed? It would be very useful to have this in the master branch so that I can have Visual Studio build the bundles as part of my build process, rather than having to manually build and import the taquito_beacon_wallet.js file to my project.

**Comment by dsawali** [comment]
Hey @oldominion, it was closed back then because the bundle was tested in a browser import directly but wasn't working as intended. But I'm glad the contents of this bundle worked for your problem. 

May I ask how you are building Taquito locally for your Blazor project? If this does get merged to master, we will also upload the bundle as a .zip file on a release.

**Comment by oldominion** [comment]
I just built with..
```
cd Taquito\taquito\packages\taquito-beacon-wallet 
npm run build-webpack or npx webpack --config webpack.config.js
```
..then imported the taquito_beacon_wallet.js file via <script> tag as described earlier.

**Review by dsawali — APPROVED** [review]

**Pull request merged**
