### PR TITLE
refactor(sapling): small refactors

### PR DESCRIPTION
**Pull request by roxaneletourneau**
Moved some files in specific folders to make the package cleaner

Thank you for your contribution to Taquito.

Before submitting this PR, please make sure:

- [ ] Your code builds cleanly without any errors or warnings
- [ ] You have added unit tests
- [ ] You have added integration tests (if relevant/appropriate)
- [ ] All public methods or types have TypeDoc coverage with a complete description, and ideally an @example
- [ ] You have added or updated corresponding documentation
- [ ] If relevant, you have written a first draft summary describing the change for inclusion in Release Notes. 

## Release Note Draft Snippet

__If relevant, please write a summary of your change that will be suitable for
inclusion in the Release Notes for the next Taquito release.__

### CODE REVIEW

**Comment by dsawali** [comment]
could we combine `helpers.ts` and `utils.ts` in this case?

**Review by zainen — APPROVED** [review]
LGTM i'll do better at remembering my semicolons 😅 
and the preference is to have `'` rather than `"` from what im getting. I will do better at remembering that since I'm more used to having it as `"`

**Comment by roxaneletourneau** [comment]
> could we combine `helpers.ts` and `utils.ts` in this case?

the utils file only has functions used by the sapling state, so I put the file inside the sapling-sate folder.
The helpers file is used by the sapling-tx-viewer, so I created a sapling-tx-viewer where I put the file.

**Comment by roxaneletourneau** [comment]
> LGTM i'll do better at remembering my semicolons sweat_smile and the preference is to have `'` rather than `"` from what im getting. I will do better at remembering that since I'm more used to having it as `"`

This is an autoformatting that is applied when I run "npm run commit", not sure why it is not doing the same formatting on your side @zainen

**Comment by dsawali** [comment]
@roxaneletourneau Ah okay that's fair. I don't really have a strong preference, it's just that they have a similar usage semantically. I think it's okay to keep it separate for now. If there are overlaps in the future we could look into combining them and putting them higher in the scope

**Review by dsawali — APPROVED** [review]

**Pull request merged**
