### PR TITLE
@taquito/remote-signer: replace libsodium with much smaller minified libraries

### PR DESCRIPTION
**Pull request by Geo25rey**
Thank you for your contribution to Taquito.

Before submitting this PR, please make sure:

- [x] Your code builds cleanly without any errors or warnings
- [x] You have added unit tests
- [x] You have added integration tests (if relevant/appropriate)
- [x] All public methods or types have TypeDoc coverage with a complete description, and ideally an @example
- [x] You have added or updated corresponding documentation
- [x] If relevant, you have written a first draft summary describing the change for inclusion in Release Notes. 

## Release Note Draft Snippet

@taquito/remote-signer: remove `libsodium` and replace with `@stablelib/blake2b` and `@stablelib/ed25519` to make the minified version significantly smaller (from ~780kB to ~300kB)

### CODE REVIEW

**Comment by Geo25rey** [comment]
@kjaiswal can you take a look at this? it's pretty short. Thanks!

**Comment by Geo25rey** [comment]
@jevonearth Are you planning on reviewing this? This PR is blocking my team.

**Comment by jevonearth** [comment]
Hi @Geo25rey 

Thank you so much for the PR!

StableLib looks like a good move for us, and personally, I'm really keen on merging this. There's some due diligence we need to do on the lib, and its maintainers before we can responsibly merge this request. I'm working on that at the moment, and I'm also coordinating with other teams in the ecosystem that presently use libsodium that may benefit from this change too.

I'm curious what specific blocker does this remove for your project? This context is useful to us.

Do you know how stablelib relates to tweetnacl? THey are from the same author. If you are aware of any public audits of stabellib, that would also help me.

We might consider making a parallel release of Taquito with the `stablelib` for a while.

**Comment by Geo25rey** [comment]
> I'm curious what specific blocker does this remove for your project? This context is useful to us.

My team uses [Ceramic](ceramic.network) as our main framework to store user profile data in a web3 manner, and we recently submitted a [PR](https://github.com/ceramicnetwork/js-ceramic/pull/1555) to include Tezos in their ecosystem. That PR depends on Taquito for standard interfaces and Taquito Remote Signer for validating signed messages. I am aware that the Remote Signer is not intended to be used as a way to validate signatures created from Tezos wallets, but it is the best solution I have found that includes all the various public key algorithms that Tezos supports.

The specific blocker is the PR we submitted to Ceramic will not be accepted since the package that we included the Remote Signer as a dependency needs to remain relatively small since it should be able to run in a web browser. In my digging around in the source code for `libsodium`, I found it is actually a large C library bundled into WebAssembly, so I'm sure most of the space used by it was wasted anyway. The perk of using `stablelib` is that it is packaged into small modules rather than having to import everything, most of which you don't actually use.

> Do you know how stablelib relates to tweetnacl? THey are from the same author. 

I didn't realize there was any relation between stablelib and tweetnacl. It seems that most development for tweetnacl has ceased, since it hasn't been updated in 2 years, but it might still be receiving security updates, I'm not sure. Stablelib seems to have more active development and the focus of the main developer. Tweetnacl is certainly not dead the main developer still responses to issues. I can switch it to tweetnacl, if you prefer.

The reason I used stablelib over tweetnacl is that the Ceramic team recommended it. I can ask them what the difference is. They would probably know more.

> If you are aware of any public audits of stabellib, that would also help me.

I am not aware of any public audits of stablelib, but tweetnacl has an audit from 2017 and there has been changes to the code since then. So both would probably need a new audit at this point.

> We might consider making a parallel release of Taquito with the `stablelib` for a while.

That would work for me. Whatever way we can get this released the fastest. Thanks!

**Comment by jevonearth** [comment]
Thank you @Geo25rey for the additional context.

We will make a feature branch release with your changes to get you unblocked. We will update you here.

In parallel to that, I will continue to do some research and due diligence on stabllib. The maintainers of beacon-sdk may also be interested in swapping out their use of libsodium for stablelib too.

**Comment by roxaneletourneau** [comment]
Thank you @Geo25rey for this PR and the context. 
Here is the released version with your changes as Jev mention above: https://www.npmjs.com/package/@taquito/remote-signer/v/9.2.0-stablelib.0
Let us know if you have any issues!

**Comment by Geo25rey** [comment]
Thanks @jevonearth and @roxaneletourneau let us know if you need any!

**Comment by roxaneletourneau** [comment]
Will be addressed by [PR#1263](https://github.com/ecadlabs/taquito/pull/1263) where libsodium is replaced by stablelib in the other packages too.

**Pull request closed without merging**
