### PR TITLE
Contract Type Generator - Tezos Toolkit Typing [Request for feedback]

### PR DESCRIPTION
**Pull request by ricklove**
#784 
This PR is to demonstrate the usage of the generated types and how they will work with the TezosToolkit (adding generics to the TezosToolkit to carry the types to the right places).

## Example Description

example/example-tezos-toolkit-contract-type.ts

The type is set in the constructor (using unknown for default):

```ts
const tezos = new TezosToolkit<TestContract>('rpc://...');
```

Based on a contract type with methods and storage (which would be generated from a contract):

```ts
type TestContract = {
    methods: {
        bid: (params: { amount: string }) => void;
        sell: (params: { id: string }) => void;
    },
    storage: {
        isTrue: boolean;
        values: MichelsonMap<string, { id: string, isOpen: boolean }>;
    }
};
```

This then provides type checking:

```ts
const accessWallet = async () => {
    // Contract
    const wallet = await tezos.wallet.at('tz123');

    // Test Storage
    const storage = await wallet.storage();
    const firstValue = storage.values.get('0');
    if (firstValue) {
        const firstId = firstValue.id;
        console.log('firstId', { firstId })
    }

    // Test Methods
    const methods = wallet.methods;
    methods.bid({ amount: '10' });
    methods.sell({ id: '42' });
};
await accessWallet();
```

image

### CODE REVIEW

**Comment by ricklove** [comment]
The usage of `any` in the default types is required for backwards compatibility.

**Comment by ricklove** [comment]
> ## DeepCode's analysis on [#044959](https://www.deepcode.ai/app/gh/ecadlabs/taquito/672bae845cbbf73d250cb136400b28e432d49d53/ecadlabs/taquito/0449598d052dee331e4be451d86a186b59aaac45/pr/_/%2F/code/?utm_source=gh_review&c=0&w=0&i=1&) found:
> * ℹ️ **1** minor issue. 👇
> 
> ## Top issues
> Description	Example fixes
> Type declaration of 'any' loses type-safety. Consider replacing it with a more precise type. Occurrences:
> * [interface.ts:101](https://github.com/ecadlabs/taquito/blob/0449598d052dee331e4be451d86a186b59aaac45/packages/taquito/src/contract/interface.ts#L101)
> * [wallet.ts:86](https://github.com/ecadlabs/taquito/blob/0449598d052dee331e4be451d86a186b59aaac45/packages/taquito/src/wallet/wallet.ts#L86)
> * [wallet.ts:109](https://github.com/ecadlabs/taquito/blob/0449598d052dee331e4be451d86a186b59aaac45/packages/taquito/src/wallet/wallet.ts#L109)
> 
> [🔧 Example fixes](https://www.deepcode.ai/app/gh/ecadlabs/taquito/672bae845cbbf73d250cb136400b28e432d49d53/ecadlabs/taquito/0449598d052dee331e4be451d86a186b59aaac45/pr/_/%2Fpackages%2Ftaquito%2Fsrc%2Fcontract%2Finterface.ts/javascript%2Ftslint%2Fno-any/code/?utm_source=gh_review&)
> #### 👉 View analysis in [**DeepCode’s Dashboard**](https://www.deepcode.ai/app/gh/ecadlabs/taquito/672bae845cbbf73d250cb136400b28e432d49d53/ecadlabs/taquito/0449598d052dee331e4be451d86a186b59aaac45/pr/_/%2F/code/?utm_source=gh_review&c=0&w=0&i=1&) | [_Configure the bot_](https://www.deepcode.ai/app/gh/?ownerconfig=ecadlabs)

The usage of any in the default types is required for backwards compatibility.

**Comment by shekhar-shubhendu** [comment]
@ricklove I tried your work and it seems to work nicely on the 2 contracts I tried on. But it only worked without error if I used `JSON` and failed when I tried `tz` format.

**Comment by ricklove** [comment]
> @ricklove I tried your work and it seems to work nicely on the 2 contracts I tried on. But it only worked without error if I used `JSON` and failed when I tried `tz` format.
> 
> Also, why is this marked as blocked?

This is still a WIP to some degree, also there are some issues with the CI that need to be cleaned up. However, you might try the latest build and see if it handles the tz contracts (see the latest private repo build).

**Comment by shekhar-shubhendu** [comment]
> > @ricklove I tried your work and it seems to work nicely on the 2 contracts I tried on. But it only worked without error if I used `JSON` and failed when I tried `tz` format.
> > Also, why is this marked as blocked?
> 
> This is still a work in progress to some degree, also there are some issues with the CI that need to be cleaned up. However, you might try the latest build and see if it handles the tz contracts (see the latest preview npm build).

Thanks. I will take a look :)

**Comment by zachrbrown** [comment]
I've encountered an issue with method signature generation in one of [`@tqtezos/minter-contracts`'s](https://github.com/tqtezos/minter-sdk) contracts. In particular, [`fa2_multi_ft_asset`](https://github.com/tqtezos/minter-sdk/blob/main/packages/minter-contracts/ligo/src/minter_collection/ft/fa2_multi_ft_asset.mligo).

The type-generated by the `type-generator` is as follows:

```ts
import { address, BigMap, bytes, contract, MMap, nat, unit } from './type-aliases';
declare type Storage = {
    admin: {
        admin: address;
        paused: boolean;
        pending_admin?: address;
    };
    assets: {
        ledger: BigMap<{
            0: address;
            1: nat;
        }, nat>;
        operators: BigMap<{
            0: address;
            1: address;
            2: nat;
        }, unit>;
        token_metadata: BigMap<nat, {
            token_id: nat;
            token_info: MMap<string, bytes>;
        }>;
        token_total_supply: BigMap<nat, nat>;
    };
    metadata: BigMap<string, bytes>;
};
declare type Methods = {
    confirm_admin: () => Promise<void>;
    pause: (param: boolean) => Promise<void>;
    set_admin: (param: address) => Promise<void>;
    balance_of: (requests: Array<{
        owner: address;
        token_id: nat;
    }>, callback: contract) => Promise<void>;
    transfer: (param: Array<{
        from_: address;
        txs: Array<{
            to_: address;
            token_id: nat;
            amount: nat;
        }>;
    }>) => Promise<void>;
    add_operator: (owner: address, operator: address, token_id: nat) => Promise<void>;
    remove_operator: (owner: address, operator: address, token_id: nat) => Promise<void>;
    burn_tokens: (param: Array<{
        owner: address;
        token_id: nat;
        amount: nat;
    }>) => Promise<void>;
    create_token: (token_id: nat, token_info: MMap<string, bytes>) => Promise<void>;
    mint_tokens: (param: Array<{
        owner: address;
        token_id: nat;
        amount: nat;
    }>) => Promise<void>;
};
export declare type Fa2MultiFtAssetContractType = {
    methods: Methods;
    storage: Storage;
    code: {
        __type: 'Fa2MultiFtAssetCode';
        protocol: string;
        code: object[];
    };
};
export {};

```

If you compare to the entry points in the [`fa2_multi_ft_token` ligo](https://github.com/tqtezos/minter-sdk/blob/main/packages/minter-contracts/ligo/src/minter_collection/ft/fa2_multi_ft_token.mligo#L100), you'll see the above generated type is missing the `Update_operators` entry point.

**Comment by jevonearth** [comment]
Superseded by upcoming Taqueria plugin and #1343

**Pull request closed without merging**
