### PR TITLE
chore: update lerna and dependencies

### LINKED ISSUE #2612: Upgrade Taquito dependencies except axios
Upgrade Taquito to use Lerna v7 after v17.3.0 release.
Update all other dependencies except axios.

Refer to their release notes for more information: https://github.com/lerna/lerna/releases/tag/7.0.0

### PR DESCRIPTION
**Pull request by AlirezaHaghshenas**
Update Lerna and related dependencies to latest version
closes #2612 

- [x] Your code builds cleanly without any errors or warnings
- [x] You have run the linter against the changes
- [ ] You have added unit tests (if relevant/appropriate)
- [ ] You have added integration tests (if relevant/appropriate)
- [ ] All public methods or types have TypeDoc coverage with a complete description, and ideally an @example
- [ ] You have added or updated corresponding documentation
- [ ] If relevant, you have written a first draft summary describing the change for inclusion in Release Notes. 

In this PR, please also make sure: 

- [x] You have linked this PR to the issue by putting `closes #TICKETNUMBER` in the description box (when applicable)
- [x] You have added a concise description on your changes

### CODE REVIEW

**Review by hui-an-yang — COMMENTED** [review]
have we tried all pacakge.json commands related to lerna and release process commands to know that it works as before?

**Comment by AlirezaHaghshenas** [comment]
> have we tried all pacakge.json commands related to lerna and release process commands to know that it works as before?

I have tried everything short of actually releasing. We can test that when trying to do the next release

**Comment by hui-an-yang** [comment]
Just hope it's not too late to found incompatibility when releasing

**Comment by AlirezaHaghshenas** [comment]
> Just hope it's not too late to found incompatibility when releasing

Do you have any suggestion?

**Comment by dsawali** [comment]
@AlirezaHaghshenas @hui-an-yang the upgrade seems to be fine judging from this build https://github.com/ecadlabs/taquito/actions/runs/6409735868/job/17401558342?pr=2687

although I am still a bit hesitant on merging this right now.

**Comment by AlirezaHaghshenas** [comment]
> @AlirezaHaghshenas @hui-an-yang the upgrade seems to be fine judging from this build https://github.com/ecadlabs/taquito/actions/runs/6409735868/job/17401558342?pr=2687
> 
> although I am still a bit hesitant on merging this right now.

What do we need to get more confidence?

**Comment by AlirezaHaghshenas** [comment]
This can be closed in favor of #2693

**Pull request closed without merging**
