### PR TITLE
Fix issue #1652

### PR DESCRIPTION
**Pull request by dvkam**
## Release Note Draft Snippet

This closes issue #1652.

✅ - Adjusted the source icons to have a transparent background, so it looks well in both light and dark modes.

✅ - **TZIP-10 column caption can be the same as the other ones:** I removed the link in the column caption and put it above the table in the sentence _Wallets that support the TZIP-10..._
This way no changes in the CSS styles were needed.

✅ - **Can the font for the tables be increased? It looks very tiny in comparison to the rest of the text. NOTE: This applies to the style of all the tables on the website. Hopefully, this just needs to be changed in 1 place.**
Thi was just a change in one place in `tables.scss` (`font-size: 16px;`). I increased it from `12px` to `16px`. But if any other size is preferred please let me know.

Screenshot dark mode:
grafik

Light mode:
grafik

Thank you for your contribution to Taquito.

Before submitting this PR, please make sure:

- [x] Your code builds cleanly without any errors or warnings
- [ ] You have run the linter against the changes
- [ ] You have added unit tests (if relevant/appropriate)
- [ ] You have added integration tests (if relevant/appropriate)
- [ ] All public methods or types have TypeDoc coverage with a complete description, and ideally an @example
- [ ] You have added or updated corresponding documentation
- [ ] If relevant, you have written a first draft summary describing the change for inclusion in Release Notes. 

In this PR, please also make sure: 

- [x] You have linked this PR to the issue by putting `closes #TICKETNUMBER` in the description box (when applicable)
- [ ] You have added a concise description on your changes

### CODE REVIEW

**Comment by dsawali** [comment]
Hello @dvkam, your contribution is much appreciated! 

The code looks good, but it seems that there's a merge conflict. Do you mind rebasing with current master?

**Comment by dvkam** [comment]
Hey @dsawali should be done. Let me know if there is anything else!

**Comment by dsawali** [comment]
Thank you @dvkam, the files changed seem to have a lot of the things that already exist in master but highlighted as 'changed'. Kinda weird 🤔

**Comment by hui-an-yang** [comment]
Hi @dvkam, 

We really appreciate your contribution to make our website better 🙌. 
I created a new branch off our current master am hopping that you can point your current pr to branch `support-dvkam-contribution-of-website-adjustments`. 
This way that we can review your changes clearly and can see the website deploy preview. 
We'd like to review and merge your changes soon. 
Thanks you so much!

**Comment by dvkam** [comment]
Hello @hui-an-yang thank you for your help. I just pointed the pr to branch `support-dvkam-contribution-of-website-adjustments`.

Not sure what happened, I suppose I did something wrong during rebase with master. Now looking at changed files it looks good. 
Thanks!

**Pull request merged**
